STYLE_RESET = 0

COLOR_BG_DEFAULT = 49
COLOR_FG_DEFAULT = 39

COLOR_FG_BLACK = 30
COLOR_FG_RED = 31
COLOR_FG_GREEN = 32
COLOR_FG_YELLOW = 33
COLOR_FG_BLUE = 34
COLOR_FG_MAGENTA = 35
COLOR_FG_CYAN = 36
COLOR_FG_WHITE = 37

COLOR_FG_BLACK_BRIGHT = 90
COLOR_FG_RED_BRIGHT = 91
COLOR_FG_GREEN_BRIGHT = 92
COLOR_FG_YELLOW_BRIGHT = 99
COLOR_FG_BLUE_BRIGHT = 94
COLOR_FG_MAGENTA_BRIGHT = 95
COLOR_FG_CYAN_BRIGHT = 96
COLOR_FG_WHITE_BRIGHT = 97

ALL_FG_COLORS = [
    COLOR_FG_BLACK,
    COLOR_FG_RED,
    COLOR_FG_GREEN,
    COLOR_FG_YELLOW,
    COLOR_FG_BLUE,
    COLOR_FG_MAGENTA,
    COLOR_FG_CYAN,
    COLOR_FG_WHITE,

    COLOR_FG_BLACK_BRIGHT,
    COLOR_FG_RED_BRIGHT,
    COLOR_FG_GREEN_BRIGHT,
    COLOR_FG_YELLOW_BRIGHT,
    COLOR_FG_BLUE_BRIGHT,
    COLOR_FG_MAGENTA_BRIGHT,
    COLOR_FG_CYAN_BRIGHT,
    COLOR_FG_WHITE_BRIGHT,
]

COLOR_BG_BLACK = 40
COLOR_BG_RED = 41
COLOR_BG_GREEN = 42
COLOR_BG_YELLOW = 43
COLOR_BG_BLUE = 44
COLOR_BG_MAGENTA = 45
COLOR_BG_CYAN = 46
COLOR_BG_WHITE = 47

COLOR_BG_BLACK_BRIGHT = 100
COLOR_BG_RED_BRIGHT = 101
COLOR_BG_GREEN_BRIGHT = 102
COLOR_BG_YELLOW_BRIGHT = 103
COLOR_BG_BLUE_BRIGHT = 104
COLOR_BG_MAGENTA_BRIGHT = 105
COLOR_BG_CYAN_BRIGHT = 106
COLOR_BG_WHITE_BRIGHT = 107

ALL_BG_COLORS = [
    COLOR_BG_BLACK,
    COLOR_BG_RED,
    COLOR_BG_GREEN,
    COLOR_BG_YELLOW,
    COLOR_BG_BLUE,
    COLOR_BG_MAGENTA,
    COLOR_BG_CYAN,
    COLOR_BG_WHITE,

    COLOR_BG_BLACK_BRIGHT,
    COLOR_BG_RED_BRIGHT,
    COLOR_BG_GREEN_BRIGHT,
    COLOR_BG_YELLOW_BRIGHT,
    COLOR_BG_BLUE_BRIGHT,
    COLOR_BG_MAGENTA_BRIGHT,
    COLOR_BG_CYAN_BRIGHT,
    COLOR_BG_WHITE_BRIGHT,
]
